name = input ('What is your name?')
print ('yaya' + name +','' ' 'my name is carybot' ':)')
age = input ('How old are you?')
print ('Wow' + ',' + age + ' ''years old! I was born today but I wish I was already dead. HA HA human jokes about depressions are funny.')
mood = input ('How was your day ?')
print ('Great! that sound good')